Action()
{

	web_url("Search Flights Button", 
		"URL=http://localhost:1080/cgi-bin/welcome.pl?page=search", 
		"TargetFrame=body", 
		"Resource=0", 
		"RecContentType=text/html", 
		"Referer=http://localhost:1080/cgi-bin/nav.pl?page=menu&in=home", 
		"Snapshot=t3.inf", 
		"Mode=HTML", 
		LAST);
	
	web_reg_save_param_ex(    
	"ParamName=OFlight",
    "LB=\"outboundFlight\" value=\"",
    "RB=\"",
    //"SaveLen=18",
    LAST);
	web_reg_save_param_ex(    
	"ParamName=RFlight",
    "LB=\"returnFlight\" value=\"",
    "RB=\"",
    //"SaveLen=18",
    LAST);
	
	web_submit_data("reservations.pl",
		"Action=http://localhost:1080/cgi-bin/reservations.pl",
		"Method=POST",
		"TargetFrame=",
		"RecContentType=text/html",
		"Referer=http://localhost:1080/cgi-bin/reservations.pl?page=welcome",
		"Snapshot=t4.inf",
		"Mode=HTML",
		ITEMDATA,
		"Name=advanceDiscount", "Value=0", ENDITEM,
		"Name=depart", "Value={City}", ENDITEM,
		"Name=departDate", "Value={Date}", ENDITEM,
		"Name=arrive", "Value={City2}", ENDITEM,
		"Name=returnDate", "Value={Date2}", ENDITEM,
		"Name=numPassengers", "Value={NumPassenger}", ENDITEM,
		"Name=roundtrip", "Value=on", ENDITEM,
		"Name=seatPref", "Value={SeatPrif}", ENDITEM,
		"Name=seatType", "Value={SeatType}", ENDITEM,
		"Name=.cgifields", "Value=roundtrip", ENDITEM,
		"Name=.cgifields", "Value=seatType", ENDITEM,
		"Name=.cgifields", "Value=seatPref", ENDITEM,
		"Name=findFlights.x", "Value=49", ENDITEM,
		"Name=findFlights.y", "Value=9", ENDITEM,
		LAST);

	web_submit_data("reservations.pl_2",
		"Action=http://localhost:1080/cgi-bin/reservations.pl",
		"Method=POST",
		"TargetFrame=",
		"RecContentType=text/html",
		"Referer=http://localhost:1080/cgi-bin/reservations.pl",
		"Snapshot=t5.inf",
		"Mode=HTML",
		ITEMDATA,
		"Name=outboundFlight", "Value={OFlight}", ENDITEM,
		"Name=returnFlight", "Value={RFlight}", ENDITEM,
		"Name=numPassengers", "Value={NumPassenger}", ENDITEM,
		"Name=advanceDiscount", "Value=0", ENDITEM,
		"Name=seatType", "Value={SeatType}", ENDITEM,
		"Name=seatPref", "Value={SeatPrif}", ENDITEM,
		"Name=reserveFlights.x", "Value=54", ENDITEM,
		"Name=reserveFlights.y", "Value=10", ENDITEM,
		LAST);

	web_submit_data("reservations.pl_3",
		"Action=http://localhost:1080/cgi-bin/reservations.pl",
		"Method=POST",
		"TargetFrame=",
		"RecContentType=text/html",
		"Referer=http://localhost:1080/cgi-bin/reservations.pl",
		"Snapshot=t6.inf",
		"Mode=HTML",
		ITEMDATA,
		"Name=firstName", "Value={FirstName}", ENDITEM,
		"Name=lastName", "Value={LastName}", ENDITEM,
		"Name=address1", "Value=Street Address 1", ENDITEM,
		"Name=address2", "Value=City1/State1/Zip1", ENDITEM,
		"Name=pass1", "Value={FirstName} {LastName}", ENDITEM,
		"Name=creditCard", "Value=1234123412341234", ENDITEM,
		"Name=expDate", "Value=555", ENDITEM,
		"Name=saveCC", "Value=on", ENDITEM,
		"Name=oldCCOption", "Value=on", ENDITEM,
		"Name=numPassengers", "Value={NumPassenger}", ENDITEM,
		"Name=seatType", "Value={SeatType}", ENDITEM,
		"Name=seatPref", "Value={SeatPrif}", ENDITEM,
		"Name=outboundFlight", "Value={OFlight}", ENDITEM,
		"Name=advanceDiscount", "Value=0", ENDITEM,
		"Name=returnFlight", "Value={RFlight}", ENDITEM,
		"Name=JSFormSubmit", "Value=off", ENDITEM,
		"Name=.cgifields", "Value=saveCC", ENDITEM,
		"Name=buyFlights.x", "Value=46", ENDITEM,
		"Name=buyFlights.y", "Value=4", ENDITEM,
		LAST);

	return 0;
}